
# --------------------------------
# Monitor configuration for external monitor
# --------------------------------

# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

monitor=eDP-1,2880x1800@60.07,0x540,2.0
monitor=eDP-1,disable

env = GDK_SCALE,2
monitor=HDMI-A-1,preferred,auto,auto

